# Generated by Django 4.2.8 on 2024-01-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('lineId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('lineName', models.CharField(max_length=255)),
                ('lineSerialNumber', models.CharField(max_length=255, null=True)),
                ('lineLocation', models.CharField(max_length=255, null=True)),
                ('lineDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('internalId', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('transportPrice', models.DecimalField(decimal_places=3, max_digits=99, null=True)),
                ('distance', models.IntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lineCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='techdocs.productionline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('offerId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('offerDate', models.DateField()),
                ('offerComponent', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=99)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
            ],
        ),
        migrations.CreateModel(
            name='MachineWorks',
            fields=[
                ('workId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('workListItemName', models.CharField(max_length=255, null=True)),
                ('workDone', models.BooleanField(null=True)),
                ('itemDescName', models.CharField(max_length=255, null=True)),
                ('itemDesc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_settings.workitemdescription')),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
                ('workListItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_settings.worklist')),
            ],
            options={
                'verbose_name_plural': 'Machine work',
            },
        ),
        migrations.CreateModel(
            name='MachineIssues',
            fields=[
                ('issueId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('issueName', models.CharField(max_length=255)),
                ('fixed', models.BooleanField(default=False)),
                ('fixTime', models.DurationField()),
                ('resolution', models.CharField(max_length=255)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
            ],
            options={
                'verbose_name_plural': 'Machine issues',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('componentId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('componentSerialNumber', models.CharField(max_length=255)),
                ('componentName', models.UUIDField()),
                ('ordered', models.BooleanField(default=False)),
                ('componentChange', models.CharField(max_length=255)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
            ],
            options={
                'verbose_name_plural': 'Components',
            },
        ),
    ]
