# Generated by Django 4.2.8 on 2024-01-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='componentPrice',
            field=models.DecimalField(decimal_places=3, max_digits=99, null=True),
        ),
    ]
