# Generated by Django 4.2.8 on 2024-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0003_alter_components_componentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
