# Generated by Django 4.2.8 on 2024-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0006_remove_machineissues_fixtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineissues',
            name='fixTime',
            field=models.IntegerField(null=True),
        ),
    ]
