# Generated by Django 4.2.8 on 2024-01-07 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0007_machineissues_fixtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('variableId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('variableName', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='workPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PriceOffer',
        ),
    ]
