# Generated by Django 4.2.8 on 2024-01-07 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0008_variables_record_workprice_delete_priceoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name_plural': 'Variables'},
        ),
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('offerId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('offerDate', models.DateField(default=django.utils.timezone.now)),
                ('workTime', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=99)),
                ('componentId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='techdocs.components')),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
            ],
        ),
    ]
