# Generated by Django 4.2.8 on 2024-01-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0009_alter_variables_options_priceoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceoffer',
            name='componentId',
        ),
        migrations.AddField(
            model_name='priceoffer',
            name='componentSerialNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
