# Generated by Django 4.2.8 on 2024-01-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0010_remove_priceoffer_componentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceoffer',
            name='componentPrice',
            field=models.DecimalField(decimal_places=3, max_digits=99, null=True),
        ),
    ]
