# Generated by Django 4.2.8 on 2024-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0011_priceoffer_componentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoffer',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=99, null=True),
        ),
    ]
