# Generated by Django 4.2.8 on 2024-01-08 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0012_alter_priceoffer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSum',
            fields=[
                ('recordSumId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('workPriceSum', models.DecimalField(decimal_places=3, max_digits=99, null=True)),
                ('componentPriceSum', models.DecimalField(decimal_places=3, max_digits=99, null=True)),
                ('transportPriceSum', models.DecimalField(decimal_places=3, max_digits=99, null=True)),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techdocs.record')),
            ],
        ),
    ]
