# Generated by Django 4.2.8 on 2024-01-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdocs', '0013_recordsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordsum',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=99, null=True),
        ),
    ]
