# Generated by Django 4.2.8 on 2024-01-04 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemDescription',
            fields=[
                ('workItemDescId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('itemId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Work list',
            },
        ),
    ]
