# Generated by Django 4.2.8 on 2024-01-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklist',
            options={'ordering': ['name'], 'verbose_name_plural': 'Work list'},
        ),
    ]
