# Generated by Django 4.2.8 on 2024-01-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_alter_worklist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitemdescription',
            options={'ordering': ['name']},
        ),
    ]
